import networkx as nx
import matplotlib.pyplot as plt
G = nx.Graph()

G.add_node('Santa Marta')
G.add_node('Neiva')
G.add_node('Medellín')
G.add_node('Bogotá')
G.add_node('Pereira')
G.add_node('Cali')
G.add_node('Barranquilla')
G.add_node('Armenia')
G.add_edge('Armenia', 'Barranquilla', weight = 4)
G.add_edge('Armenia', 'Cali', weight = 3)
G.add_edge('Barranquilla', 'Pereira', weight = 5)
G.add_edge('Cali', 'Barranquilla', weight = 2)
G.add_edge('Cali', 'Pereira', weight = 3)
G.add_edge('Cali', 'Bogotá', weight = 6)
G.add_edge('Pereira','Bogotá', weight = 5)
G.add_edge('Pereira', 'Neiva', weight = 1)
G.add_edge('Bogotá', 'Medellín', weight = 5)
G.add_edge('Medellín', 'Santa Marta', weight = 5)
G.add_edge('Neiva', 'Medellín', weight = 2)
G.add_edge('Neiva', 'Santa Marta', weight = 7)
nx.draw(G, with_labels = True)
plt.show()